In [1]:
import numpy as np

In [2]:
a = np.random.randint(2*3, size=(2,3))
a

array([[5, 2, 1],
       [3, 1, 1]])

In [3]:
a.argmin()

2

In [4]:
a.argmin(axis=0)

array([1, 1, 0])

In [5]:
a.argmin(axis=1)

array([2, 1])

In [6]:
b = np.random.randint(2*3*4, size=(2,3,4))
b

array([[[10, 20, 18, 16],
        [15,  7,  4, 23],
        [ 6, 13, 21,  3]],

       [[ 2,  6, 20, 16],
        [ 2,  9, 11,  5],
        [16, 10,  8,  4]]])

In [7]:
b.argmin()

12

In [8]:
b.argmin(axis=0)

array([[1, 1, 0, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0]])

In [9]:
b.argmin(axis=1)

array([[2, 1, 1, 2],
       [0, 0, 2, 2]])

In [10]:
b.argmin(axis=2)

array([[0, 2, 3],
       [0, 0, 3]])