In [1]:
import numpy as np

In [2]:
a = np.random.randint(2*3, size=(2,3))
a

array([[5, 5, 5],
       [3, 1, 3]])

In [3]:
a.argmax()

0

In [4]:
a.argmax(axis=0)

array([0, 0, 0])

In [5]:
a.argmax(axis=1)

array([0, 0])

In [6]:
b = np.random.randint(2*3*4, size=(2,3,4))
b

array([[[12, 11,  8, 16],
        [17,  4,  9, 19],
        [11,  5,  9,  4]],

       [[ 8,  6, 14, 16],
        [19, 20, 19, 23],
        [14,  7, 17,  2]]])

In [7]:
b.argmax()

19

In [8]:
b.argmax(axis=0)

array([[0, 0, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 0]])

In [9]:
b.argmax(axis=1)

array([[1, 0, 1, 1],
       [1, 1, 1, 1]])

In [10]:
b.argmax(axis=2)

array([[3, 3, 0],
       [3, 3, 2]])