In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b = a.reshape(-1, 1)
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
scaler = MinMaxScaler()
scaler.fit(b)

MinMaxScaler()

In [5]:
print(scaler.n_samples_seen_, scaler.data_min_, scaler.data_max_, scaler.feature_range)

5 [1.] [5.] (0, 1)


In [6]:
c = scaler.transform(b)
c

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [7]:
c.tolist()

[[0.0], [0.25], [0.5], [0.75], [1.0]]