In [1]:
import numpy as np

In [2]:
a = np.array([1, 2])
a

array([1, 2])

In [3]:
b = np.array([3, 4])
b

array([3, 4])

In [4]:
np.array([a, b])

array([[1, 2],
       [3, 4]])

In [5]:
np.column_stack([a, b])

array([[1, 3],
       [2, 4]])