In [1]:
import numpy as np

# meshgrid

In [2]:
x = np.array(np.arange(0,3))
x

array([0, 1, 2])

In [3]:
y = np.array(np.arange(3,5))
y

array([3, 4])

In [4]:
xy, yx = np.meshgrid(x,y)

In [5]:
xy

array([[0, 1, 2],
       [0, 1, 2]])

In [6]:
yx

array([[3, 3, 3],
       [4, 4, 4]])

In [7]:
ij, ji = np.meshgrid(x,y,indexing='ij')

In [8]:
ij

array([[0, 0],
       [1, 1],
       [2, 2]])

In [9]:
ji

array([[3, 4],
       [3, 4],
       [3, 4]])

# flat data for 3d plot

In [10]:
xy_flat = xy.flatten()
xy_flat

array([0, 1, 2, 0, 1, 2])

In [11]:
yx_flat = yx.flatten()
yx_flat

array([3, 3, 3, 4, 4, 4])

In [12]:
z_flat = np.zeros_like(xy).flatten()
z_flat

array([0, 0, 0, 0, 0, 0])

In [13]:
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True)
trace1 = go.Scatter3d(
    x=xy_flat,
    y=yx_flat,
    z=z_flat,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.8
    )
)
data = [trace1]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=0
    )
)
fig = go.Figure(data=data, layout=layout)
iplot(fig)