In [1]:
import pandas as pd
print(pd.__version__)

0.20.3


In [2]:
data1 = [4, 3, 1, 2]
data1

[4, 3, 1, 2]

In [3]:
# list to series
series1 = pd.Series(data1)
series1

0    4
1    3
2    1
3    2
dtype: int64

In [4]:
series1.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
series1.values

array([4, 3, 1, 2])

In [6]:
series1.dtype

dtype('int64')

In [7]:
import numpy as np
print(np.__version__)

1.13.3


In [8]:
data2 = np.array([1, 4, 2, 3], np.int32)
data2

array([1, 4, 2, 3], dtype=int32)

In [9]:
# numpy 1d array to series
series2 = pd.Series(data2)
series2

0    1
1    4
2    2
3    3
dtype: int32

In [10]:
# series index option
series2 = pd.Series(data1, index=['a', 'b', 'c', 'd'])
series2

a    4
b    3
c    1
d    2
dtype: int64

In [11]:
series2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [12]:
series2.values

array([4, 3, 1, 2])

In [13]:
series2.dtype

dtype('int64')

In [14]:
series2.name

In [15]:
series2.name = 'test2'

In [16]:
series2.name

'test2'

In [17]:
series2.index.name

In [18]:
series2.index.name = 'test2index'

In [19]:
series2.index.name

'test2index'