In [1]:
import numpy as np

In [2]:
X0 = np.array([3., 4.])
X0

array([3., 4.])

In [3]:
X1 = np.array([4.,5.])
X1

array([4., 5.])

In [4]:
X2 = np.array([X0,X1])
X2

array([[3., 4.],
       [4., 5.]])

In [5]:
def f_nditer(x):
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        print('idx =', idx, 'value =', x[idx])
        it.iternext()

In [6]:
f_nditer(X0)

idx = (0,) value = 3.0
idx = (1,) value = 4.0


In [7]:
f_nditer(X2)

idx = (0, 0) value = 3.0
idx = (0, 1) value = 4.0
idx = (1, 0) value = 4.0
idx = (1, 1) value = 5.0


In [8]:
def f_size(x):
    for idx in range(0, x.size):
        print('idx =', idx, 'value =', x[idx])

In [9]:
f_size(X0)

idx = 0 value = 3.0
idx = 1 value = 4.0


In [10]:
f_size(X2)

idx = 0 value = [3. 4.]
idx = 1 value = [4. 5.]


IndexError: index 2 is out of bounds for axis 0 with size 2